# Generated by Django 4.0.1 on 2022-01-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('MOBILE', 'Mobile Phone'), ('PC', 'PC'), ('OS', 'OS')], max_length=10, null=True),
        ),
    ]
